[tool.black]
line-length = 120

[project]
name = "project-name"
requires-python = ">=3.10"
description = "Project desc."
keywords = []
authors = [
    {name = "h-terao"}
]
dependencies = [
]
dynamic = ["version", "readme"]

